### PR TITLE
Upgraded to .net core 1.0.0, changed versioning scheme

### PR DESCRIPTION
**Pull request by SapientGuardian**

### CODE REVIEW

**Comment by eByte23** [comment]
Looks good :D

**Comment by SapientGuardian** [comment]
Not quite. Having trouble getting the latest sdk on Travis.

**Comment by eByte23** [comment]
Ahh right, looks like progress now though?

**Comment by eByte23** [comment]
Failing on trying to get System.Security.Cryptography.Native now

**Comment by SapientGuardian** [comment]
I think we might need to trigger a `brew install openssl` on the osx build, per https://github.com/dotnet/coreclr/issues/1502. Not sure how we've escaped the problem thus far.

**Comment by eByte23** [comment]
That's interesting have you tried building on linux your self if not I can now?

**Comment by SapientGuardian** [comment]
The linux build is fine, it's the osx build that has the problem. I don't have a mac to test with.

**Comment by eByte23** [comment]
Ahh that explains things! luckily I do so I'll give it a shot and see what I get, well sorta.

**Comment by eByte23** [comment]
Reproduced all steps got the exact same error, did `brew install openssl` still failed.
I will try downloading the offical mac package now

**Comment by eByte23** [comment]
Okay we need to do

```
brew update
brew install openssl
brew link --force openssl
```

if you don't do the last link command it will still fail.

Now builds for me, still don't understand how we escaped it until now, unless they changed something

**Pull request merged**
