### PR TITLE
6.9 netstandard 1.3 beta1

### PR DESCRIPTION
**Pull request by eByte23**
So I have done the basic implementation of the dotnet db interfaces and also lower our require dotnet ver to netstandard 1.3 :D (Winning)!

I will be implementing all the test also in dotnet core, so we can test how reliable the work is

Going to do more clean up and bring back code so that we can make it more approachable as a merge-able pr for mysql branch

As metioned #1

### CODE REVIEW

**Comment by SapientGuardian** [comment]
Nice work! Of course, I look pretty silly for putting 1.5 in the repo and branch name now. :flushed: 

I grabbed the package from your myget feed and tested it in my internal project that I use this for, and my tests are passing there.  :thumbsup:

I see at the moment there are some blocks of code that were removed or commented, mostly relating to RT. If I'm reading https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md correctly, winrt would require netstandard 1.1; so if it's possible to not harm the RT build, that would be good (of course, if you aren't targeting .net core I'm not sure why you'd use this fork). I've tried to keep the older style builds intact as much as possible mostly to make it easier to rebase against the upstream repo.

Some of the tests use NUnit, but there is no "dotnet test" support for NUnit yet. There's another way to run them though (https://github.com/nunit/nunit/issues/1371). It looks like some of the tests are actually using XUnit already, so all we need to do there is make a test project and exclude or port the NUnit tests. I actually hadn't noticed the XUnit tests until just now, otherwise I'd have made a test project earlier.

AppVeyor seems to be confused with this PR (https://ci.appveyor.com/project/SapientGuardian/mysql-connector-net-netstandard1-5/build/6.9.8-rc2-15), but maybe you just branched before I had the config straightened out and need to rebase.

**Comment by eByte23** [comment]
@SapientGuardian Not to worry about the 1.5 not a biggie :smile: 

Yeah my bad I just wanted it to work to start with I copied my fix and re-did it properly with almost 0 code removal/modification just ifdefs!!!!

I'll see if I can fix the rebase.

**Comment by eByte23** [comment]
With the test's I'll make another PR after this maybe just so we can get this in if you like?

**Comment by eByte23** [comment]
@SapientGuardian There we are, rebase and up to date!

**Comment by SapientGuardian** [comment]
Sold! Tests in a separate PR will be fine, especially since there aren't any right now. You'll want to wait a few minutes after I merge the PR before making a new branch; I'm going to try renaming the repo and the main branch.

**Comment by eByte23** [comment]
Awesome! I'll do it first thing in the morning :smile:

I think it will  probably be better to create a new project and convert the NUnit test over to XUnit and reuse the XUnit test or also copy them.

But I'll see how I go when Im  finished.
Thanks!

**Pull request merged**
