### PR TITLE
Fixed keywords resource

### PR DESCRIPTION
**Pull request by SapientGuardian**
This MR restores functionality of the Keywords resource.

### CODE REVIEW

**Comment by SapientGuardian** [comment]
@IntelOrca your sample repro no longer crashes with this version. Do you have a larger context you can test this in, or is that yet to be written?

**Comment by IntelOrca** [comment]
I do, but I won't be able to test that until tomorrow evening. Would it be okay for you to tag another build with this fix?

**Comment by SapientGuardian** [comment]
Will do. Even if this doesn't fix your scenario, I suspect there are others that will be helped by this.

**Comment by IntelOrca** [comment]
With the test project from #10 I now get

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at MySql.Data.MySqlClient.Properties.Resources.LoadKeywords()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at MySql.Data.MySqlClient.MySqlCommand.AddCallStatement(String query)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MySql.Data.MySqlClient.MySqlConnection.BeginTransaction(IsolationLevel iso)
   at ConsoleApplication.Program.Main(String[] args)
```

I will investigate...

**Comment by IntelOrca** [comment]
https://github.com/SapientGuardian/mysql-connector-net-netstandard/blob/6.9_netstandard/Source/MySql.Data/Properties/Resources.Designer.cs#L630

This might need to be changed to `SapientGuardian.MySql.Data.Properties.keywords.txt`

**Comment by SapientGuardian** [comment]
Well that's annoying. Fixing...

**Comment by SapientGuardian** [comment]
Fixed in SapientGuardian.MySql.Data 6.9.8-rc2-006

**Comment by IntelOrca** [comment]
thanks, it works now!

**Pull request merged**
