### PR TITLE
fixing encoding for utf-8 not english

### PR DESCRIPTION
**Pull request by kleberksms**
Likely correction for: 

https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql/issues/48

### CODE REVIEW

**Comment by SapientGuardian** [comment]
Thanks for the PR. Can you test it by using https://ci.appveyor.com/api/buildjobs/s0s7v27asjsems5r/artifacts/artifacts%2FSapientGuardian.MySql.Data%2FSapientGuardian.MySql.Data.6.9.814.nupkg to see if it fixes the problem before I merge it in?

**Comment by kleberksms** [comment]
I will do unit tests and integration as soon as I pass and do not break the code, I will post again with the results

**Comment by kleberksms** [comment]
@SapientGuardian ,  how to do include in project.json this reference "https://ci.appveyor.com/api/buildjobs/s0s7v27asjsems5r/artifacts/artifacts%2FSapientGuardian.MySql.Data%2FSapientGuardian.MySql.Data.6.9.814.nupkg"?

**Comment by SapientGuardian** [comment]
Run `nuget.exe add SapientGuardian.MySql.Data.6.9.814.nupkg -Source C:\PathToLocalNuget` to put the package in your local cache, then you can reference it like any other.

**Comment by kleberksms** [comment]
Before
before
After
after

**Comment by SapientGuardian** [comment]
Great, nice work!

**Pull request merged**
