### PR TITLE
Added MySql.Data.EntityFramework7 (EF7 Support)

### PR DESCRIPTION
**Pull request by how02**
I converted original mysql's project MySql.Data.EntityFramework7 to dotnet core.
Not entirely tested.

### CODE REVIEW

**Comment by eByte23** [comment]
@how02 nice! only thing I see is that you'll need to change the project.json not to point to the direct reference of MySQL.Data as its build incremented. So possibly needs to change to "MySql.Data": "6.9.*" ?

**Comment by SapientGuardian** [comment]
Nice work! I'm happy to take this PR, but I wonder if it wouldn't better be suited to its own repo? It doesn't actually have any dependencies on files in this repo, beyond the base mysql library (which comes in via package anyway) does it?

**Comment by IntelOrca** [comment]
You've committed project.lock.json, this should be ignored from git.

**Comment by eByte23** [comment]
True, but if oracle does want to pr this back might be nice to have it all in one? 
If it a standalone needs as I said will need version as 6.9.\* and change the package name to SapientGuardian.MySql.Data

**Comment by eByte23** [comment]
@how02 builds gonna fail because of not having target.

```
    "MySql.Data": {
      "version": "6.9.*",
      "target": "project"
    },
```

I believe

**Comment by how02** [comment]
Woops sorry, I'm not very experienced with dotnet core.

**Comment by eByte23** [comment]
All good, love the effort!

**Comment by SapientGuardian** [comment]
You're going to have to reference SapientGuardian.MySql.Data in your project.json rather than MySql.Data, because we rename the project at the last moment to change the package name. That leaves you with two effectively independent projects sitting in the same repo. Actually, it makes it even worse, because now I can't version the projects with the same number, since this one depends on the other having already been published.

In the unlikely event that Oracle wants to take what we've done (which would be awesome), they too should have split repos. Mono-repos are all kinds of terrible.

The more I think about this, the more I'm convinced that it should be separate.

**Comment by eByte23** [comment]
Your right most people do breakout their projects into multiple repos, just thought maybe because of the oracle thing, but yes very unlikely. 
Also it seems like there is a weird bug in dotnet tooling as you "should" be able to reference as type:project the way we did when you have the folder in the global.json as a project but tested it doesn't seem to work either

**Comment by SapientGuardian** [comment]
@how02 how do you feel about splitting off your project into its own repo on your own account? We can help you set up ci and nuget if you need it. If you prefer, I can set it up here on my account as SapientGuardian.MySql.Data.EntityFramework7 and publish the nuget package as my own, but you did all the work and deserve all the credit :smile:.

**Comment by eByte23** [comment]
Possibly consider a namespace change to line up with up naming convention to MySql.Data.EntityFrameworkCore

**Comment by how02** [comment]
@SapientGuardian I think it would be easier if you set it up on your own account.

**Comment by SapientGuardian** [comment]
As you wish. I've moved your project to https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql, squashing your commits in the process. I'd like to get a little testing done on it before I push it to NuGet, but the packages will be in the AppVeyor artifacts. Closing this PR; please do any subsequent work against the new repo. Thanks again for your efforts!

**Pull request closed without merging**
